name: riverpodtemp
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter

  #base:
  dio: ^5.8.0+1
  intl: ^0.20.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.9.3
  proste_indexed_stack: ^0.2.4

  auto_route: ^10.0.1
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.2
  permission_handler: ^11.4.0

  provider: ^6.1.2

  #ui
  lottie: ^3.3.1
  swipe_to: ^1.0.6
  cupertino_icons: ^1.0.8
  photo_view: ^0.15.0
  top_snackbar_flutter: ^3.2.0
  sms_autofill: ^2.4.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  flutter_remix: ^0.0.3
  connectivity_plus: ^6.1.3
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.4
  flutter_advanced_switch: ^3.1.0
  share_plus: ^10.1.4
  flutter_masked_text2: ^0.9.1
  floating_draggable_widget: ^2.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_carousel_slider: ^1.1.0
  jiffy: ^6.3.2
  flutter_staggered_animations: ^1.1.1
  upgrader: ^11.3.1
  like_button: ^2.0.5
  carousel_slider: ^5.0.0
  rating_summary: ^1.0.4
  readmore: ^3.0.0
  webview_flutter: ^4.10.0
  app_tracking_transparency: ^2.0.6+1
  intl_phone_field: ^3.2.0
  grouped_list: ^6.0.0
  shimmer: ^3.0.0
  flutter_widget_from_html: ^0.16.0

  #media:
  image: ^4.5.3
  file_picker: ^9.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  cached_network_image: ^3.4.1

  #maps:
  location: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_place:
    git:
      url: https://github.com/Muhammadyunusxon/google_place.git
  osm_nominatim: ^3.0.1
  google_maps_flutter: ^2.10.1
  map_launcher: ^3.5.0

  #firebase:
  firebase_dynamic_links: ^6.1.4
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  #auth:
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1

  payfast:
    git:
      url: https://github.com/Muhammadyunusxon/payfast_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1



flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/customer.png'
  adaptive_icon_foreground: 'assets/images/customer.png'
  adaptive_icon_background: "#ffffff"